#!/bin/bash

# 📊 Script para mostrar a estrutura criada da Nova Arquitetura
# Executa: chmod +x scripts/show-structure.sh && ./scripts/show-structure.sh

echo "🏗️ Estrutura da Nova Arquitetura Clean Architecture"
echo "=================================================="
echo ""

echo "📦 INTERNAL - Internal Packages"
echo "└── internal/"
echo "    ├── core/         # 🎯 Core Business Logic"
echo "    ├── services/     # 🔧 Application Services"
echo "    └── adapters/     # 🔌 External Connections"
echo ""
echo "🎯 CORE - Business Logic (Lógica de Negócio Pura)"
echo "├── session/          # Gerenciamento de sessões WhatsApp"
echo "├── messaging/        # Lógica de mensagens e validações"
echo "├── contacts/         # Regras de contatos"
echo "├── groups/           # Lógica de grupos e participantes"
echo "├── media/            # Regras de mídia e cache"
echo "├── newsletter/       # Lógica de newsletters"
echo "├── community/        # Regras de comunidades"
echo "├── integrations/"
echo "│   ├── chatwoot/     # Lógica de integração Chatwoot"
echo "│   └── webhook/      # Regras de webhooks"
echo "└── shared/"
echo "    ├── errors/       # Erros de domínio"
echo "    ├── events/       # Sistema de eventos"
echo "    └── types/        # Tipos compartilhados"
echo ""

echo "🔧 SERVICES - Application Services (Orquestração)"
echo "├── session_service.go      # Orquestração de sessões"
echo "├── message_service.go      # Coordenação de mensagens"
echo "├── contact_service.go      # Orquestração de contatos"
echo "├── group_service.go        # Coordenação de grupos"
echo "├── chatwoot_service.go     # Orquestração Chatwoot"
echo "├── webhook_service.go      # Coordenação webhooks"
echo "├── media_service.go        # Orquestração de mídia"
echo "├── newsletter_service.go   # Coordenação newsletters"
echo "├── community_service.go    # Orquestração comunidades"
echo "└── shared/"
echo "    ├── validation/         # Validações de entrada"
echo "    └── mapping/            # DTOs e mapeamentos"
echo ""

echo "🔌 ADAPTERS - External Connections (Conexões Externas)"
echo "├── http/"
echo "│   ├── handlers/           # REST API handlers"
echo "│   ├── middleware/         # Middlewares HTTP"
echo "│   └── routes/             # Configuração de rotas"
echo "├── database/"
echo "│   ├── postgres/           # Implementações Repository"
echo "│   └── migrations/         # Migrações de banco"
echo "├── whatsapp/               # Gateway WhatsApp"
echo "├── chatwoot/               # Gateway Chatwoot"
echo "└── events/                 # Event Publishers"
echo ""

echo "🚀 CMD - Entry Points (Pontos de Entrada)"
echo "├── server/                 # HTTP Server"
echo "├── worker/                 # Background workers"
echo "└── cli/                    # CLI tools"
echo ""

echo "🧪 TESTS - Test Structure (Estrutura de Testes)"
echo "├── core/                   # Testes unitários do core"
echo "├── services/               # Testes de services"
echo "├── adapters/               # Testes de adapters"
echo "├── integration/            # Testes de integração"
echo "├── e2e/                    # Testes end-to-end"
echo "└── helpers/                # Helpers e mocks"
echo ""

echo "📋 SCRIPTS - Automation (Automação)"
echo "├── validate-architecture.sh   # Validar regras arquiteturais"
echo "├── check-dependencies.sh      # Verificar dependências"
echo "├── test-coverage.sh           # Cobertura de testes"
echo "├── generate-mocks.sh          # Gerar mocks"
echo "└── run-migrations.sh          # Executar migrações"
echo ""

echo "📚 DOCS - Documentation (Documentação)"
echo "├── architecture/           # Documentação arquitetural"
echo "├── api/                    # Documentação da API"
echo "└── development/            # Guias de desenvolvimento"
echo ""

echo "📊 ESTATÍSTICAS:"
echo "   🎯 Core: $(find internal/core -name "*.go" 2>/dev/null | wc -l) arquivos Go"
echo "   🔧 Services: $(find internal/services -name "*.go" 2>/dev/null | wc -l) arquivos Go"
echo "   🔌 Adapters: $(find internal/adapters -name "*.go" 2>/dev/null | wc -l) arquivos Go"
echo "   🚀 CMD: $(find cmd -name "*.go" 2>/dev/null | wc -l) arquivos Go"
echo "   🧪 Tests: $(find tests -name "*.go" 2>/dev/null | wc -l) arquivos de teste"
echo "   📋 Scripts: $(find scripts -name "*.sh" 2>/dev/null | wc -l) scripts"
echo ""

echo "✅ Estrutura criada seguindo Clean Architecture!"
echo "📖 Consulte MIGRATION_PLAN.md para próximos passos"
